name: post-status
run-name: Post status update
on: 
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
 
jobs:
  send-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dafnik/setup-node-pnpm@v1
        with:
          node: '18'
          pnpm: 8
      - run: "pnpm i"
      - run: "pnpm build"
      - run: "pnpm start"
        env:
          ACCESS_TOKEN: ${{ secrets.MASTO_ACCESS_TOKEN }}
          MASTODON_URL: ${{ vars.MASTO_URL_ENDPOINT }}
